### ISSUE TITLE
TypeError: Cannot read property 'unifiedDiff' of undefined

### ISSUE THREAD

**Issue by atomanyih** [horvay/jasmine-snapshot#1]
Heya

Tried to pull this in on a react project using jasmine and got the titular error

I think there's a problem with how you are importing `difflib`.
I see from [jasmine-snapshot/src/index.ts](https://github.com/horvay/jasmine-snapshot/blob/master/src/index.ts) that you are importing the default export in es6
`import difflib from 'difflib';`

But in [difflib/src/difflib.coffee](https://github.com/qiao/difflib.js/blob/master/src/difflib.coffee) it doesn't use the module syntax, so it looks like there's no default export

Went and mucked with the minified, transpiled source in `jasmine-snapshot.min.js` to change from `difflib.default.unifiedDiff` to `difflib.unifiedDiff` and it started working

Obviously changing minified code is sketch but maybe `index.ts` should read `import * as difflib from 'difflib'`?

**Comment by horvay** [comment]
Interesting. I'll look into this tomorrow.

We are currently using this library at my work. You are using Karma and Jasmine?

BTW, I'm updating the documentation tomorrow as well, as I changed quite a bit over the weekend. But everything in the documentation should still work.

**Comment by horvay** [comment]
That worked. I've updated the import to what you suggested.

I guess webpack was doing some voodoo for me to make it work even though there was no default export.

Thanks for the catch.
