### ISSUE TITLE
Doesn't work with jasmine node CLI

### ISSUE THREAD

**Issue by wmhilton** [horvay/jasmine-snapshot#5]
I'd like to use this snapshot library with the "jasmine" node CLI as well as in the browser. Could you add some checks so I don't run into "window is not defined" and "document is not defined"? (I'm trying to switch from jest to Jasmine, and want to have a single test suite that works in both environments.)

**Comment by horvay** [comment]
I'll look into this but I have 2 full time jobs atm. Feel free to submit a pull request if it's super straight forward.

**Comment by wmhilton** [comment]
No sweat! I might just work around it for now - but if I get a chance to fix it I'll definitely make a PR.

**Comment by jtisekar** [comment]
I ran into the same issue. Created a Pull request the removes the reference to windows.console. Let me know your thoughts on it
